FROM ppc64le/golang:1.21.1-alpine3.18 AS build
WORKDIR /app
COPY go.mod go.sum ./
COPY exporter.go ./
RUN go mod download
RUN go build -o app

FROM ppc64le/alpine:latest
WORKDIR /
COPY --from=build /app/app .
#RUN chmod +x /app/app
EXPOSE 9100
ENTRYPOINT ["/app"]